### ISSUE TITLE
install() broken??

### ISSUE THREAD

**Issue by KevinAlavik** [tidev/node-ios-device#83]
seems to not work

**Comment by KevinAlavik** [comment]
/Users/kevin/Desktop/fxck-apple/node_modules/node-ios-device/src/index.js:82
        binding.install(udid, appPath);
         ^
Error: Failed to install app on device (0xe800002d)
    at EventEmitter.install (/Users/kevin/Desktop/fxck-apple/node_modules/node-ios-device/src/index.js:82:10)
    at fxck (file:///Users/kevin/Desktop/fxck-apple/fxckapple.js:29:13)
    at main (file:///Users/kevin/Desktop/fxck-apple/fxckapple.js:120:5)
    at file:///Users/kevin/Desktop/fxck-apple/fxckapple.js:133:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)

**Comment by cb1kenobi** [comment]
This is not a `node-ios-device` error. You can Google `"0xe800002d"` and see that this is an iOS error that can occur a number of different ways.

I have no idea what the problem is, but it could be the app is not compatible with the device, the app isn't signed properly, the cable is bad, there's an issue with the entitlements, etc. Maybe Apple doesn't like your app name. :)

Regardless, there's a near-zero chance the problem is with `node-ios-device`.

**Comment by KevinAlavik** [comment]
The cables is probably the reason
